### ISSUE TITLE
StackOverflow Exceptions with Dragon Tribute Reduction

### ISSUE THREAD

**Issue by Rauell** [adambennett/StS-DuelistMod#46]
When playing with the dragon decks, I've run into some stack overflow exceptions involving the `modifyTributesForApexFeralTerritorial` (logs below). This appears to occur when playing an `Apex` card with [Cyber Dragon](https://www.duelistmetrics.com/#/cards/details/theDuelist:CyberDragon) or [Atomic Scrap Dragon](https://www.duelistmetrics.com/#/cards/details/theDuelist:AtomicScrapDragon).

From looking at those two cards, it looks like the `tributeReduction` methods are attempting to check if the calling card has its own tribute cost modified, causing the infinite loop. A simple fix would be to exclude self from that check. I've opened https://github.com/adambennett/StS-DuelistMod/pull/45 with a fix. 

I'm not familiar with modding StS and from a quick look at the repo, I didn't find any tests, so I'm not sure how to test the changes.

[atomic_scrap_dragon.log](https://github.com/adambennett/StS-DuelistMod/files/13931968/atomic_scrop_dragon.log)
[cyber_end_dragon.log](https://github.com/adambennett/StS-DuelistMod/files/13931970/cyber_end_dragon.log)

**Comment by adambennett** [comment]
Thanks @Rauell! Unfortunately I haven't spent any time setting up a testing suite since it would involve some additional complexities with stubbing the game functionality, so all testing must be performed manually by recompiling the mod and running the game with the updated version. I'd be happy to do this step for you as I appreciate the investigation you have already done here. I'll take a look and see if I can reproduce in the current build and then apply your fix and see if it works.

**Comment by Rauell** [comment]
Thanks for doing the testing @adambennett! Makes sense that the actual testing requires re-compiling and running the mod.

**Comment by adambennett** [comment]
Ok @Rauell, the code is working now. I implemented a slightly different fix after some testing where I noticed the bug was still occurring when you had both Atomic Scrap Dragon and Cyber End Dragon in your hand at the same time as an Apex card. 

It appears to be working as expected now, as Atomic Scrap Dragon will count the number of Cyber End Dragons in hand and reduce tribute cost by that number if there are additional tribute-modified cards in hand, since in this case Cyber End Dragons will also be modified as well. Cyber End Dragon simply skips checking all Atomic Scrap Dragons and Cyber End Dragons, since if either of those cards are modified there must be at least 1 other modified card in hand, so no need to check the infinite loop cards.

These fixes will go up with the next steam workshop release, or if you're impatient you can compile the latest dev branch now and it should be working. Thanks for the report! Interesting edge case that I did not consider originally.
